# Generated by Django 3.0 on 2019-12-17 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Adresse Email')),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='Pseudo')),
                ('first_name', models.CharField(max_length=30, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nom')),
                ('is_active', models.BooleanField(default=True, verbose_name='Utilisateur actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Admin')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('first_connection', models.BooleanField(default=True, verbose_name='Premiere connection')),
                ('confirm', models.BooleanField(default=False)),
                ('confirmation_date', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Pizzy Utilisateur',
                'verbose_name_plural': 'Pizzy Utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('None', 'Non communiqué'), ('Woman', 'Femme'), ('Man', 'Homme')], default='None', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='private_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
